# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_id',
            new_name='clas',
        ),
        migrations.RenameField(
            model_name='tea_cla',
            old_name='class_id',
            new_name='clas',
        ),
        migrations.RenameField(
            model_name='tea_cla',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='tea_cla',
            unique_together=set([('teacher', 'clas')]),
        ),
    ]
